### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by kskim7714** [triforkse/atom-elm#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [elm](https://github.com/triforkse/atom-elm) package, v0.1.0
### Stack Trace

Uncaught TypeError: Bad argument

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:262

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (internal/child_process.js:274:26)
  at Object.exports.spawn (child_process.js:374:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:190:44)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at Object.format (/Users/tom/.atom/packages/elm/lib/elm.js:96:5)
  at Object.formatCurrentFile (/Users/tom/.atom/packages/elm/lib/elm.js:81:12)
  at atom-workspace.elmFormatFile (/Users/tom/.atom/packages/elm/lib/elm.js:32:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
  at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)

```
### Commands

```
     -2:54.7.0 application:new-file (atom-workspace.workspace.theme-one-dark-syntax.theme-one-dark-ui.scrollbars-visible-always.find-visible)
     -2:52.7.0 core:save (atom-text-editor.editor.is-focused.power-mode)
     -2:37.6.0 settings-view:open (atom-text-editor.editor.power-mode.is-focused)
     -2:31 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:05.8.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -2:05.0 core:save (atom-text-editor.editor.power-mode.is-focused)
 21x -2:03.5.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -2:01.1.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -1:58.3.0 application:new-file (atom-text-editor.editor.mini.is-focused)
     -1:57.7.0 core:save (atom-text-editor.editor.is-focused.power-mode)
  7x -1:52.7.0 core:backspace (atom-text-editor.editor.is-focused.power-mode)
     -1:50 core:save (atom-text-editor.editor.is-focused.power-mode)
     -1:44 core:backspace (atom-text-editor.editor.is-focused.power-mode)
     -0:18.9.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
     -0:18.2.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:00.8.0 elm-format:file (atom-text-editor.editor.power-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "vim-mode"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
auto-detect-indentation, v1.1.0
color-picker, v2.1.1
elm, v0.1.0
language-elm, v1.5.0
language-scala, v1.1.6
nuclide, v0.141.0
pigments, v0.29.2
remote-edit, v1.8.24
term3, v0.22.0

# Dev
No dev packages
```

**Comment by pholisma** [comment]
[Enter steps to reproduce below:]

1. Open .elm file in Atom
2. Select Packages->elm-format->Format this file

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Linux Mint
**Thrown From**: [elm](https://github.com/triforkse/atom-elm) package, v0.1.0


### Stack Trace

Uncaught TypeError: Bad argument

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:353

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:392:9)
    at BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:282:51)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:117:12)
    at Object.format (/home/blimpse/.atom/packages/elm/lib/elm.js:96:5)
    at Object.formatCurrentFile (/home/blimpse/.atom/packages/elm/lib/elm.js:81:12)
    at atom-workspace.elmFormatFile (/home/blimpse/.atom/packages/elm/lib/elm.js:32:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1175:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:319:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
 12x -3:25.5.0 core:backspace (input.hidden-input)
  3x -3:20.8.0 core:confirm (input.hidden-input)
  2x -1:25.1.0 elm-format:file (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ariake-dark-syntax, v0.1.3 (inactive)
duotone-dark-sea-syntax, v2.1.0 (inactive)
elm, v0.1.0 (active)
elmjutsu, v3.2.1 (active)
flexible-ui, v0.10.7 (inactive)
gloom, v0.4.4 (inactive)
language-elm, v1.5.0 (active)
min-ui, v0.0.1 (inactive)
monokai, v0.20.0 (inactive)
ramda-syntax, v0.12.0 (inactive)
react, v0.16.2 (active)
seafoam-syntax, v2.2.0 (inactive)
vim-mode-plus, v0.82.0 (active)
zenburn, v3.1.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (active)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (active)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by benjick** [comment]
The package `elm` should be de-listed. Try installing `elm-format`

**Comment by boxed** [comment]
Atom suggests the bad one above.. can this be removed?
